import os

this_dir = os.path.dirname(__file__)
ini_path = os.path.join(this_dir, "imgui.ini")
out_path = os.path.join(this_dir, "src/imgui_ini.h")

with open(ini_path, "r") as f:
    ini_content = f.read()
with open(out_path, "w") as f:
    f.write("// Auto-generated by update_imgui_ini.py\n")
    f.write("const char* IMGUI_DEFAULT_INI = R\"(\n")
    f.write(ini_content)
    f.write(")\";\n")
