// Auto-generated by update_imgui_ini.py
const char* IMGUI_DEFAULT_INI = R"(
[Window][WindowOverViewport_11111111]
Pos=0,0
Size=1920,1027
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Log]
Pos=0,553
Size=410,474
Collapsed=0
DockId=0x00000008,1

[Window][CPU]
Pos=1486,0
Size=434,514
Collapsed=0
DockId=0x00000004,0

[Window][RAM]
Pos=1486,516
Size=434,511
Collapsed=0
DockId=0x00000006,0

[Window][PPU]
Pos=1412,0
Size=508,514
Collapsed=0
DockId=0x00000004,1

[Window][SPRITES]
Pos=0,0
Size=410,551
Collapsed=0
DockId=0x00000007,2

[Window][PALETTE]
Pos=0,0
Size=410,551
Collapsed=0
DockId=0x00000007,3

[Window][PATTERN TABLE]
Pos=0,0
Size=410,551
Collapsed=0
DockId=0x00000007,0

[Window][NAMETABLE]
Pos=0,0
Size=410,551
Collapsed=0
DockId=0x00000007,1

[Window][Screen]
Pos=469,0
Size=937,1027
Collapsed=0
DockId=0x00000003,0

[Window][APU]
Pos=1486,0
Size=434,514
Collapsed=0
DockId=0x00000004,1

[Window][DISPLAY]
Pos=412,0
Size=1072,1027
Collapsed=0
DockId=0x00000003,0

[Window][CPU MAP]
Pos=1486,516
Size=434,511
Collapsed=0
DockId=0x00000006,1

[Window][PPU MAP]
Pos=1486,516
Size=434,511
Collapsed=0
DockId=0x00000006,2

[Window][Control]
Pos=0,553
Size=410,474
Collapsed=0
DockId=0x00000008,0

[Docking][Data]
DockSpace       ID=0x08BD597D Window=0x1BBC0F80 Pos=0,0 Size=1920,1027 Split=X Selected=0xDD2D1825
  DockNode      ID=0x00000005 Parent=0x08BD597D SizeRef=1484,1027 Split=X
    DockNode    ID=0x00000002 Parent=0x00000005 SizeRef=410,1027 Split=Y Selected=0x3C120CB1
      DockNode  ID=0x00000007 Parent=0x00000002 SizeRef=467,551 Selected=0x3C120CB1
      DockNode  ID=0x00000008 Parent=0x00000002 SizeRef=467,474 Selected=0xC6859269
    DockNode    ID=0x00000003 Parent=0x00000005 SizeRef=1072,1027 CentralNode=1 Selected=0xF953D106
  DockNode      ID=0x00000001 Parent=0x08BD597D SizeRef=434,1027 Split=Y Selected=0x2316D1C6
    DockNode    ID=0x00000004 Parent=0x00000001 SizeRef=512,514 Selected=0xD74E07A8
    DockNode    ID=0x00000006 Parent=0x00000001 SizeRef=512,511 Selected=0x9669B933

)";
